#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target_file="${VOLCENGINE_ENV_FILE:-${project_root}/agent/.env.local}"
resource_id="${VOLCENGINE_RESOURCE_ID:-volc.service_type.10053}"

fail() {
  printf '错误：%s\n' "$1" >&2
  exit 1
}

read_required_secret() {
  local prompt="$1"
  local value
  IFS= read -r -s -p "$prompt" value
  printf '\n' >&2
  [[ -n "$value" ]] || fail "该字段不能为空。"
  printf '%s' "$value"
}

read_optional_secret() {
  local prompt="$1"
  local value
  IFS= read -r -s -p "$prompt" value
  printf '\n' >&2
  printf '%s' "$value"
}

printf '%s\n' '配置火山引擎 AST 2.0 本地测试凭据'
printf '%s\n' '凭据只会写入 agent/.env.local，不会显示在终端，也不会提交到 Git。'
printf '%s\n' ''
printf '%s\n' '请选择控制台凭据类型：'
printf '%s\n' '  1) 新版 API Key（推荐）'
printf '%s\n' '  2) 旧版 APP ID + Access Token'
IFS= read -r -p '请输入 1 或 2: ' auth_mode

api_key=''
app_id=''
access_token=''
secret_key=''

case "$auth_mode" in
  1)
    api_key="$(read_required_secret 'API Key: ')"
    ;;
  2)
    IFS= read -r -p 'APP ID: ' app_id
    [[ -n "$app_id" ]] || fail 'APP ID 不能为空。'
    access_token="$(read_required_secret 'Access Token: ')"
    secret_key="$(read_optional_secret 'Secret Key（可选，AST WebSocket 运行时不使用；直接回车跳过）: ')"
    ;;
  *)
    fail '只能选择 1 或 2。'
    ;;
esac

mkdir -p "$(dirname "$target_file")"
umask 077
tmp_file="$(mktemp "${target_file}.tmp.XXXXXX")"
cleanup() {
  rm -f "$tmp_file"
}
trap cleanup EXIT HUP INT TERM

{
  printf '# Generated by scripts/setup-volcengine-env.sh; do not commit.\n'
  if [[ "$auth_mode" == '1' ]]; then
    printf 'VOLCENGINE_API_KEY=%q\n' "$api_key"
  else
    printf 'VOLCENGINE_APP_ID=%q\n' "$app_id"
    printf 'VOLCENGINE_ACCESS_TOKEN=%q\n' "$access_token"
    if [[ -n "$secret_key" ]]; then
      printf 'VOLCENGINE_SECRET_KEY=%q\n' "$secret_key"
    fi
  fi
  printf 'VOLCENGINE_RESOURCE_ID=%q\n' "$resource_id"
} >"$tmp_file"

chmod 600 "$tmp_file"
mv -f "$tmp_file" "$target_file"
trap - EXIT HUP INT TERM

permission="$(stat -c '%a' "$target_file")"
[[ "$permission" == '600' ]] || fail "凭据文件权限应为 600，实际为 ${permission}。"

if git -C "$project_root" check-ignore -q -- "$target_file"; then
  ignore_status='已被 Git 忽略'
else
  fail '凭据文件未被 Git 忽略，请勿继续使用或提交。'
fi

printf '\n配置完成。\n'
printf '文件：%s\n' "$target_file"
printf '权限：%s\n' "$permission"
printf 'Git：%s\n' "$ignore_status"
printf '模式：%s\n' "$([[ "$auth_mode" == '1' ]] && printf '新版 API Key' || printf '旧版 APP ID + Access Token')"
printf '\n启动 Local Agent：\n'
printf '  cd %q\n' "$project_root"
printf '  set -a; source agent/.env.local; set +a\n'
printf '  cd agent && go run ./cmd/translator-agent\n'
